# docker-compose.yml example
# LEGACY CONFIGURATION
# SEE README FOR INFORMATIONS

tor:
  image: goldy/tor-hidden-service:$CUR_TAG
  links:
    - hello
    - world
  environment:
      PORT_MAP: 80 # Map port to detected service
  volumes:
    - ./keys:/var/lib/tor/hidden_service/

hello:
  image: tutum/hello-world
  hostname: hello

world:
  image: tutum/hello-world
  hostname: world
