version: "3.7"

services:
  tor:
    #image: goldy/tor-hidden-service:v0.4.1.6-3cf37e1
    build:
      context: tor    
    networks: 
        node:
          ipv4_address: 172.28.7.10
    environment:
      # Enable Socks proxy on 9050
      SOCKS: "true"

      # Enable Control Port on 9051
      CONTROL: "true"

      # Set mapping ports
      HELLO_TOR_SERVICE_HOSTS: 80:hello:9898,9898:hello:9898
      # Set private key set from secret
      #HELLO_TOR_SERVICE_KEY: ${KEY}
      HELLO_TOR_SERVICE_VERSION: 3

    # Keep keys in volumes
    volumes:
      - tor-keys:/var/lib/tor/hidden_service/
      - tor-control:/var/lib/tor/control/

    secrets:
      - source: hello_key
        target: hello

  bitcoind:
    build:
      context: bitcoind
    depends_on:
      - tor
    networks:
      - node
    environment:
      BITCOIN_DATA: "/data"
      BITCOIN_WALLET_DISABLE: "true"

    volumes:
      - /mnt/bitcoind:/data
      - tor-control:/var/lib/tor/control/

  hello:
    image: primeroz/podinfo-arm7:latest
    depends_on:
      - tor
    networks: 
      - node

networks:
  node:
   ipam:
     config:
       - subnet: 172.28.7.0/24

volumes:
  tor-keys:
    driver: local
  tor-control:
    driver: local

secrets:
  hello_key:
    file: /tmp/key
