version: "3.7"

services:
  tor:
    #image: goldy/tor-hidden-service:v0.4.1.6-3cf37e1
    build:
      context: tor    
    networks: 
        node:
          ipv4_address: 172.28.7.10
    environment:
      # Enable Socks proxy on 9050
      SOCKS: "true"

      # Set mapping ports
      BTC_TOR_SERVICE_HOSTS: 8332:bitcoind:8332,8333:bitcoind:8333
      #BTC_TOR_SERVICE_HOSTS: 8333:bitcoind:8333
      BTC_TOR_SERVICE_VERSION: 3

    # Keep keys in volumes
    volumes:
      - tor-keys:/var/lib/tor/hidden_service/

    secrets:
      - source: tor_key
        target: hello

  bitcoind:
    build:
      context: bitcoind
    depends_on:
      - tor
    networks:
      - node
    environment:
      BITCOIN_DATA: "/data"
      BITCOIN_WALLET_DISABLE: "true"
    entrypoint: 
      - /wait-for
    command: "\"tor:9050\" -- /entrypoint.sh bitcoind"
    volumes:
      - /mnt/bitcoind:/data

networks:
  node:
   ipam:
     config:
       - subnet: 172.28.7.0/24

volumes:
  tor-keys:
    driver: local

secrets:
  tor_key:
    file: /tmp/key
